#!/bin/bash

if [ "$1" = "" ]; then
  if [ "$PT_REPO_PATH" = "" ]; then echo "PT_REPO_PATH not set!" ; exit 1 ; fi
  if [ "$PT_BINDIR" = "" ];    then echo "PT_BINDIR not set!" ; exit 1 ; fi
  if [ "$PT_BIT" = "" ];       then echo "PT_BIT not set!" ; exit 1 ; fi
  THEBINDIR=$PT_REPO_PATH/$PT_BINDIR
else
  THEBINDIR=$1
fi

if [ ! -d $THEBINDIR ]; then mkdir $THEBINDIR ; fi

echo "Updating data files in \"$THEBINDIR\" ..."

cd $THEBINDIR && \
rm -rf ChannelMixers Curves LensfunDatabase Presets Profiles Translations UISettings && \
mkdir  ChannelMixers Curves LensfunDatabase Presets Profiles Translations UISettings && \
cd $PT_REPO_PATH && \
cp -r ./ChannelMixers/*    $THEBINDIR/ChannelMixers && \
cp -r ./Curves/*           $THEBINDIR/Curves && \
cp -r ./LensfunDatabase/*  $THEBINDIR/LensfunDatabase && \
cp -r ./Presets/*          $THEBINDIR/Presets && \
cp -r ./Profiles/*         $THEBINDIR/Profiles && \
cp -r ./Translations/*.qm  $THEBINDIR/Translations && \
cp -r ./UISettings/*       $THEBINDIR/UISettings

exitstatus=$?
if [ ! ${exitstatus} -eq 0 ] && [ "$1" == "" ]; then echo "Failed!" ; fi
exit ${exitstatus}

#rm Themes
#mkdir Themes
#cp -r ../Themes/*           ./Themes &&
