#!/bin/bash

PT_CP_DEST_OPTS=--preserve=timestamps

if [ "$PT_REPO_PATH" = "" ]; then echo "PT_REPO_PATH not set!" ; exit 1 ; fi
if [ "$PT_BINDIR" = "" ];    then echo "PT_BINDIR not set!" ; exit 1 ; fi
if [ "$PT_BIT" = "" ];       then echo "PT_BIT not set!" ; exit 1 ; fi

if [ "$1" != "" ]; then
  THEBINDIR="$1"
else
  if [ ! -d "$PT_REPO_PATH" ]; then
    echo "Path to repository \"$PT_REPO_PATH\" not found."
    exit 1
  fi
  THEBINDIR="$PT_REPO_PATH/$PT_BINDIR"
fi


echo "Updating all DLLs in $THEBINDIR ... "

if [ ! -d "$THEBINDIR" ]; then
  mkdir "$THEBINDIR"
else
  rm -f "$THEBINDIR/*.dll"
fi

if [ "$PT_BIT" = "64" ]; then
  cd /mingw/qt/bin
  cp QtCore4.dll \
     QtGui4.dll \
     QtNetwork4.dll \
     $THEBINDIR $PT_CP_DEST_OPTS

  cd /mingw/bin
  cp libgcc_s_sjlj_64-1.dll \
     libgomp_64-1.dll \
     libstdc++_64-6.dll \
     pthreadGC2_64.dll \
     $THEBINDIR $PT_CP_DEST_OPTS

  cd /my/bin
  cp lensfun.dll \
     libexiv2.dll \
     libexpat-1.dll \
     libfftw3-3.dll \
     libfreetype-6.dll \
     libglib-2.0-0.dll \
     libGraphicsMagick-3.dll \
     libGraphicsMagick++-3.dll \
     libGraphicsMagickWand-2.dll \
     libiconv-2.dll \
     libintl-8.dll \
     libjpeg-8.dll \
     liblcms2-2.dll \
     liblqr-1-0.dll \
     libpng15-15.dll \
     libtiff-3.dll \
     zlib1.dll \
     $THEBINDIR $PT_CP_DEST_OPTS

elif [ "$PT_BIT" = "32" ]; then
  cd /mingw/qt/bin
  cp QtCore4.dll \
     QtGui4.dll \
     QtNetwork4.dll \
     $THEBINDIR $PT_CP_DEST_OPTS

  cd /mingw/bin
  cp libgcc_s_sjlj-1.dll \
     libgomp-1.dll \
     libstdc++-6.dll \
     pthreadGC2.dll \
     $THEBINDIR $PT_CP_DEST_OPTS

  cd /my/bin
  cp freetype6.dll \
     intl.dll \
     lensfun.dll \
     libexiv2.dll \
     libexpat-1.dll \
     libfftw3-3.dll \
     libglib-2.0-0.dll \
     libGraphicsMagick-3.dll \
     libGraphicsMagick++-3.dll \
     libGraphicsMagickWand-2.dll \
     libiconv-2.dll \
     libjpeg-8.dll \
     liblcms2-2.dll \
     liblqr-1-0.dll \
     libpng15-15.dll \
     libtiff-3.dll \
     zlib1.dll \
     $THEBINDIR $PT_CP_DEST_OPTS

else
  echo "Wrong PT_BIT ($PT_BIT)."
  exit 1
fi